Aggregation means summarizing data:

Example:

Total sales
Average Revenue
Frequency counts

In [2]:
#GroupBy
import pandas as pd

data = {
    "Customer": ["Asha","Bala","Chitra","Deepa","Esha","Farhan","Gita","Hari"],
    "City": ["Bangalore","Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore"],
    "Product": ["Laptop","Mobile","Laptop","Tablet","Mobile","Laptop","Tablet","Mobile"],
    "Sales": [50000,30000,45000,20000,32000,47000,22000,31000],
    "Quantity": [2,1,1,3,2,1,2,1]
}

df = pd.DataFrame(data)

df

  Customer       City Product  Sales  Quantity
0     Asha  Bangalore  Laptop  50000         2
1     Bala      Delhi  Mobile  30000         1
2   Chitra     Mumbai  Laptop  45000         1
3    Deepa      Delhi  Tablet  20000         3
4     Esha  Bangalore  Mobile  32000         2
5   Farhan     Mumbai  Laptop  47000         1
6     Gita      Delhi  Tablet  22000         2
7     Hari  Bangalore  Mobile  31000         1

In [3]:
#Group by works with split,apply,combine logic
#Total Sales by city
df.groupby("City")["Sales"].sum()

City
Bangalore    113000
Delhi         72000
Mumbai        92000
Name: Sales, dtype: int64

In [ ]:
#count transactions per city
df.groupby("City")["Sales"].count()

City
Bangalore    3
Delhi        3
Mumbai       2
Name: Sales, dtype: int64

In [5]:
#Sales by city and product
df.groupby(["City","Product"])["Sales"].sum()

City       Product
Bangalore  Laptop     50000
           Mobile     63000
Delhi      Mobile     30000
           Tablet     42000
Mumbai     Laptop     92000
Name: Sales, dtype: int64

In [7]:
df.groupby(["Product","City"])["Sales"].sum()

Product  City
Laptop   Bangalore    50000
         Mumbai       92000
Mobile   Bangalore    63000
         Delhi        30000
Tablet   Delhi        42000
Name: Sales, dtype: int64

In [8]:
#multiple aggregations
#using .agg()

df.groupby("City").agg({
    "Sales":"sum",
    "Quantity":"mean"
})

            Sales  Quantity
City
Bangalore  113000  1.666667
Delhi       72000  2.000000
Mumbai      92000  1.000000

In [9]:
#multiple aggregations on same column

df.groupby("City")["Sales"].agg(["sum","mean","max","min"])

              sum          mean    max    min
City
Bangalore  113000  37666.666667  50000  31000
Delhi       72000  24000.000000  30000  20000
Mumbai      92000  46000.000000  47000  45000

In [ ]:
#groupby size vs count

df.groupby("City").size()   #counts number of rows per group

df.groupby("City")["Sales"].count()  #counts non null values in sales column

City
Bangalore    3
Delhi        3
Mumbai       2
Name: Sales, dtype: int64

In [12]:
#pivot tables
#Pivot tables reshape data like excel pivot tables

pd.pivot_table(df,values="Sales",
                  index="City",
                  columns="Product",
                  aggfunc="sum")

Product     Laptop   Mobile   Tablet
City
Bangalore  50000.0  63000.0      NaN
Delhi          NaN  30000.0  42000.0
Mumbai     92000.0      NaN      NaN

In [13]:
#pivot table with multiple aggregations
pd.pivot_table(df,values="Sales",
                  index="City",
                  columns="Product",
                  aggfunc=["sum","mean"])

               sum                       mean
Product     Laptop   Mobile   Tablet   Laptop   Mobile   Tablet
City
Bangalore  50000.0  63000.0      NaN  50000.0  31500.0      NaN
Delhi          NaN  30000.0  42000.0      NaN  30000.0  21000.0
Mumbai     92000.0      NaN      NaN  46000.0      NaN      NaN

In [ ]:
#crosstab
#crosstab counts occurrences it's also called frequency table

pd.crosstab(df["City"],df["Product"])

#This gives us product popularity in each city

Product    Laptop  Mobile  Tablet
City
Bangalore       1       2       0
Delhi           0       1       2
Mumbai          2       0       0

In [3]:
#pivot table with multiple values

pd.pivot_table(df,values=["Sales","Quantity"],
               index="City",
               columns="Product",
               aggfunc="sum")

          Quantity                  Sales
Product     Laptop Mobile Tablet   Laptop   Mobile   Tablet
City
Bangalore      2.0    3.0    NaN  50000.0  63000.0      NaN
Delhi          NaN    1.0    5.0      NaN  30000.0  42000.0
Mumbai         2.0    NaN    NaN  92000.0      NaN      NaN

In [ ]:
#pivot table with fill values
pd.pivot_table(df,values="Sales",
               index="City",
               columns="Product",
               aggfunc="sum",
               fill_value=0)

#replace NaN with zero

Product    Laptop  Mobile  Tablet
City
Bangalore   50000   63000       0
Delhi           0   30000   42000
Mumbai      92000       0       0