In [27]:
import pandas as pd
import numpy as np

data={
    'Customer_name':['Asha','Bala','Chitra','Deepa','Esha','Bala','Bala','Bala'],
    'City':['Bangalore','Delhi','Mumbai','Delhi','Bangalore','Delhi','Delhi','Delhi'],
    'Order_value':[5000,7000,np.nan,6500,7200,7000,7000,7000],
    'Email':['asha123@gmail.com','bala@gmail.com','chitra@company.com',
             'deepa_98@yahoo.com','esha@gmail.com','bala@gmail.com',
             'bala@gmail.com','bala@gmail.com']
}

df=pd.DataFrame(data)
df

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
2        Chitra     Mumbai          NaN  chitra@company.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com
5          Bala      Delhi       7000.0      bala@gmail.com
6          Bala      Delhi       7000.0      bala@gmail.com
7          Bala      Delhi       7000.0      bala@gmail.com

Handling duplicate values

Duplicates occur when the same record appears multiple times in a dataset.

Common reasons:
Data entry errors
Merging datasets
System logging errors

Duplicates can distort the analysis,for example:
Revenue may appear higher than reality

In [ ]:
#identifying duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [ ]:
#viewing duplicate rows
df[df.duplicated()]

  Customer_name   City  Order_value           Email
5          Bala  Delhi       7000.0  bala@gmail.com

In [9]:
#removes completely identical rows
df.drop_duplicates(inplace=True)
df

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
2        Chitra     Mumbai          NaN  chitra@company.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [15]:
#using subset

df1=df.drop_duplicates(subset='Email')
df1
#this removes duplicates only based on the Email column

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [ ]:
#keep decides which duplicate record remains
df1=df.drop_duplicates(keep=False)
df1

#keep parameter accepts only three values-first,last,false

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
2        Chitra     Mumbai          NaN      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [24]:
#string operations with .str

#text columns in pandas can use the .str accessor which allows vectorized string operations

df['City'].str.lower()

0    bangalore
1        delhi
2       mumbai
3        delhi
4    bangalore
5        delhi
6        delhi
7        delhi
Name: City, dtype: str

In [28]:
df[df['Email'].str.contains('gmail')]

  Customer_name       City  Order_value              Email
0          Asha  Bangalore       5000.0  asha123@gmail.com
1          Bala      Delhi       7000.0     bala@gmail.com
4          Esha  Bangalore       7200.0     esha@gmail.com
5          Bala      Delhi       7000.0     bala@gmail.com
6          Bala      Delhi       7000.0     bala@gmail.com
7          Bala      Delhi       7000.0     bala@gmail.com

In [ ]:
df['Customer_name'].str.strip()
#removes extra spaces
#useful when data comes from forms or Excel sheets

0      Asha
1      Bala
2    Chitra
3     Deepa
4      Esha
5      Bala
6      Bala
7      Bala
Name: Customer_name, dtype: str

In [30]:
df['Email'].str.replace('gmail.com','gmail.co')

0      asha123@gmail.co
1         bala@gmail.co
2    chitra@company.com
3    deepa_98@yahoo.com
4         esha@gmail.co
5         bala@gmail.co
6         bala@gmail.co
7         bala@gmail.co
Name: Email, dtype: str

In [32]:
df[df['Email'].str.startswith('a')]

  Customer_name       City  Order_value              Email
0          Asha  Bangalore       5000.0  asha123@gmail.com

In [34]:
df['Email'].str.split('@')

0     [asha123, gmail.com]
1        [bala, gmail.com]
2    [chitra, company.com]
3    [deepa_98, yahoo.com]
4        [esha, gmail.com]
5        [bala, gmail.com]
6        [bala, gmail.com]
7        [bala, gmail.com]
Name: Email, dtype: object

In [38]:
df['Greeting']="Hello"+" "+df['Customer_name']
print(df['Greeting'])

0      Hello Asha
1      Hello Bala
2    Hello Chitra
3     Hello Deepa
4      Hello Esha
5      Hello Bala
6      Hello Bala
7      Hello Bala
Name: Greeting, dtype: str

In [ ]:
#Regex - Regular expressions
#to extract patterns from text

Common regex patterns

\d     digit
\w     letter or number
^      start of a string
$      end of string
.      any character
+      one or more
*      zero or more


commonly used with -
.str.contains()
.str.extract()
.str.replace()
.str.match()

In [12]:
import pandas as pd

data={"Email":["asha123@gmail.com",
              "bala@gmail.com",
              "chitra@company.com,"
              "deepa_98@yahoo.com"]}
df=pd.DataFrame(data)

In [2]:
#extract numbers from text

df["Email"].str.extract(r"(\d+)")

     0
0  123
1  NaN
2   98

In [3]:
#find rows containing numbers
df["Email"].str.contains(r"\d")

0     True
1    False
2     True
Name: Email, dtype: bool

In [4]:
#extract email domain
df["Email"].str.extract(r"@(\w+)")

         0
0    gmail
1    gmail
2  company

when we write @(\w+)

()       capture group
\w       letter or number
+        one or more

here match starts at the symbol @ but since @ is outside of the capture group it is not extracted
so only what is inside the capture group() is extracted

In [6]:
#Find emails ending with gmail.com

df["Email"].str.contains(r"@gmail\.com$")

0     True
1     True
2    False
Name: Email, dtype: bool

In [7]:
data={"Name":["Asha","Bala","Chitra","Deepa"]}
df=pd.DataFrame(data)

In [10]:
#Find names starting with A
df["Name"].str.contains(r"^A")

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [16]:
#remove numbers from emails
df["Email"].str.replace(r"\d","",regex=True)

0                         asha@gmail.com
1                         bala@gmail.com
2    chitra@company.com,deepa_@yahoo.com
Name: Email, dtype: str

In [17]:
#Regex groups
#deepa_98@gmail.com
#we want to extract both name and number in the email separately

df["Email"].str.extract(r"(\w+)_(\d+)")

       0    1
0    NaN  NaN
1    NaN  NaN
2  deepa   98