Concatenation- pd.concat()

Concatenation means combining dataframes by stacking them

Two main ways to stack:

vertical stacking        axis=0
horizontal stacking      axis=1

In [1]:
import pandas as pd

df1=pd.DataFrame({
    "Customer":["Asha","Bala"],
    "City":["Bangalore","Mumbai"]
})
df1

  Customer       City
0     Asha  Bangalore
1     Bala     Mumbai

In [2]:
df2=pd.DataFrame({
    "Customer":["Chitra","Deepa"],
    "City":["Delhi","Mumbai"]
})
df2

  Customer    City
0   Chitra   Delhi
1    Deepa  Mumbai

In [6]:
#stack rows
#vertical stackings or adding more rows

pd.concat([df1,df2],axis=0)

  Customer       City
0     Asha  Bangalore
1     Bala     Mumbai
0   Chitra      Delhi
1    Deepa     Mumbai

In [7]:
pd.concat([df1,df2],axis=0).reset_index(drop=True)

  Customer       City
0     Asha  Bangalore
1     Bala     Mumbai
2   Chitra      Delhi
3    Deepa     Mumbai

In [8]:
df3=pd.DataFrame({"Sales":[50000,30000]})

df4=pd.DataFrame({"Quantity":[2,1]})

In [ ]:
#Horizontal stacking or adding more columns
pd.concat([df3,df4],axis=1)

   Sales  Quantity
0  50000         2
1  30000         1

In [ ]:
#vertical concatenation

#dataframe 1
import pandas as pd

jan=pd.DataFrame({
    "Customer":["Asha","Sanjana"],
    "City":["Bangalore","Mumbai"],
    "Sales":[5000,7000]
})
print(jan)
print()

#dataframe 2
feb=pd.DataFrame({
    "Customer":["Chris","Deepak"],
    "City":["Delhi","Kolkata"],
    "Sales":[6500,7200]
})
print(feb)

  Customer       City  Sales
0     Asha  Bangalore   5000
1  Sanjana     Mumbai   7000

  Customer     City  Sales
0    Chris    Delhi   6500
1   Deepak  Kolkata   7200

In [6]:
pd.concat([jan,feb],axis=0).reset_index(drop=True)

  Customer       City  Sales
0     Asha  Bangalore   5000
1  Sanjana     Mumbai   7000
2    Chris      Delhi   6500
3   Deepak    Kolkata   7200

In [9]:
#horizontal stacking
customers=pd.DataFrame({
    "Customers":["Asha","Bala","Chitra"]
})

sales=pd.DataFrame({
    "Sales":[5000,7000,8000]
})

pd.concat([customers,sales],axis=1)

  Customers  Sales
0      Asha   5000
1      Bala   7000
2    Chitra   8000

In [13]:
#when columns don't match
#pandas aligns columns by name
df1=pd.DataFrame({
    "Customer":["Asha","Bala"],
    "Sales":[5000,6000]
})

df2=pd.DataFrame({
    "Customer":["Chitra","Deepa"],
    "Profit":[9000,10000]
})

pd.concat([df1,df2]).reset_index(drop=True).fillna("no value")

  Customer     Sales    Profit
0     Asha    5000.0  no value
1     Bala    6000.0  no value
2   Chitra  no value    9000.0
3    Deepa  no value   10000.0

Merging(combining tables)-

Merge is used when data is stored in separate tables but linked by keys

Syntax-
pd.merge(left_df,right_df,on="column")

In [33]:
customers=pd.DataFrame({
    "CustomerID":[1,2,3],
    "CustomerName":["Asha","Deepa","Chiranth"],
    "City":["Bangalore","Kolkata","Jaipur"]
})
print(customers)
print()
orders=pd.DataFrame({
    "CustomerID":[1,2,4],
    "OrderValue":[5000,7000,6500]
})
print(orders)

   CustomerID CustomerName       City
0           1         Asha  Bangalore
1           2        Deepa    Kolkata
2           3     Chiranth     Jaipur

   CustomerID  OrderValue
0           1        5000
1           2        7000
2           4        6500

In [ ]:
pd.merge(customers,orders,on="CustomerID")
#this will match rows where customer ID exists in both tables

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore        5000
1           2        Deepa    Kolkata        7000

In [17]:
#when column names dont match

df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})

In [18]:
pd.merge(df1,df2,left_on="custID",right_on="CustomerID")

   custID    Name  CustomerID  Sales
0       1  Anusha           1   5000
1       2  Rajesh           2   7000

In [25]:
#to remove extra key column while merging
#you can rename the column before merge
df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})

df2=df2.rename(columns={"CustomerID":"custID"})
pd.merge(df1,df2,on="custID")

   custID    Name  Sales
0       1  Anusha   5000
1       2  Rajesh   7000

In [26]:
#to remove extra key column while merging
#you can drop one column after merging

df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})

result=pd.merge(df1,df2,left_on="custID",right_on="CustomerID")
result.drop(columns="CustomerID")

   custID    Name  Sales
0       1  Anusha   5000
1       2  Rajesh   7000

In [28]:
#to remove extra key column while merging
#you can select columns while merging
df1=pd.DataFrame({
    "custID":[1,2],
    "Name":["Anusha","Rajesh"]
})

df2=pd.DataFrame({
    "CustomerID":[1,2],
    "Sales":[5000,7000]
})

pd.merge(df1,df2,left_on="custID",right_on="CustomerID")[["custID","Name","Sales"]]

   custID    Name  Sales
0       1  Anusha   5000
1       2  Rajesh   7000

In [ ]:
#join types
#Join types control which rows remain after merge

#inner join- only matching rows

pd.merge(customers,orders,on="CustomerID",how="inner")

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore        5000
1           2        Deepa    Kolkata        7000

In [ ]:
#right join-matching rows and all rows from right table

pd.merge(customers,orders,on="CustomerID",how="right")

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore        5000
1           2        Deepa    Kolkata        7000
2           4          NaN        NaN        6500

In [31]:
#left join-matching rows and all rows from left table

pd.merge(customers,orders,on="CustomerID",how="left")

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore      5000.0
1           2        Deepa    Kolkata      7000.0
2           3     Chiranth     Jaipur         NaN

In [32]:
#outer join - all rows from both tables
pd.merge(customers,orders,on="CustomerID",how="outer")

   CustomerID CustomerName       City  OrderValue
0           1         Asha  Bangalore      5000.0
1           2        Deepa    Kolkata      7000.0
2           3     Chiranth     Jaipur         NaN
3           4          NaN        NaN      6500.0

In [37]:
#joining through multiple keys

sales=pd.DataFrame({
    "CustomerID":[1,1,2],
    "Product":["Laptop","Mobile","Tablet"],
    "Sales":[5000,3000,7000]
})

prices=pd.DataFrame({
    "CustomerID":[1,2],
    "Product":["Laptop","Tablet"],
    "Discount":[10,15]
})

pd.merge(sales,prices,on=["CustomerID","Product"])

   CustomerID Product  Sales  Discount
0           1  Laptop   5000        10
1           2  Tablet   7000        15

In [ ]:
#Duplicate keys

df1=pd.DataFrame({
    "ID":[1,1],
    "Name":["Asha","Asha"]
})

df2=pd.DataFrame({
    "ID":[1,1],
    "Sales":[5000,6000]
})

pd.merge(df1,df2,on="ID")

#many to many join

   ID  Name  Sales
0   1  Asha   5000
1   1  Asha   6000
2   1  Asha   5000
3   1  Asha   6000

In [41]:
#suffixes 
#when both tables contain same column name

df1=pd.DataFrame({
    "ID":[1,2],
    "Sales":[5000,7000]
})

df2=pd.DataFrame({
    "ID":[1,2],
    "Sales":[3000,4000]
})

pd.merge(df1,df2,on="ID",suffixes=("_store1","_store2"))

   ID  Sales_store1  Sales_store2
0   1          5000          3000
1   2          7000          4000