#data transformation

.map() replaces values using a dictionary mapping

Map in pandas is used to transform or substiture values in a single column(series)
using a mapping rule.
Commonly used in data cleaning or feature engineering

syntax- series.map(mapping)

here mapping can be another:

dictionary
a function
another series

In [11]:
import pandas as pd
data={"City":
    ["Bangalore","Delhi","Mumbai"]
}
df=pd.DataFrame(data)
df

        City
0  Bangalore
1      Delhi
2     Mumbai

In [12]:
#convert city names to regions
region_map={"Bangalore":"South",
            "Delhi":"North",
            "Mumbai":"West"
            }

df["Region"]=df["City"].map(region_map)
df

        City Region
0  Bangalore  South
1      Delhi  North
2     Mumbai   West

In [ ]:
#mapping using a function

#.map() can apply a function to each value

df["City_length"]=df["City"].map(len)
df

        City Region  City_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai   West            6

In [17]:
#mapping through a series
city_series=pd.Series({"Bangalore":"South",
                        "Delhi":"North",
                        "Mumbai":"West"})

df["Region"]=df["City"].map(city_series)
df

        City Region  City_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai   West            6

In [ ]:
#mapping with missing values
#when there are missing values its filled with NaN
region_map={"Bangalore":"South",
            "Delhi":"North",
            }

df["Region"]=df["City"].map(region_map)
df

        City Region  City_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai    NaN            6

In [20]:
#filling missing values using map

df["Region"]=df["City"].map(region_map).fillna("Other")
df

        City Region  City_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai  Other            6

In [ ]:
import pandas as pd
import numpy as np

data={"Customer":["Asha","Bala","Chitra"],
      "Sales":[50000,30000,15000]}

df=pd.DataFrame(data)

In [12]:
#Applying custom functions
#.apply() lets us run custom logic on rows or columns

#example- classify sales performance

def sales_category(x):
    if x>40000:
        return "High"
    elif x>25000:
        return "Medium"
    else:
        return "Low"
    
#apply function

df["Sales_Category"]=df["Sales"].apply(sales_category)
df

  Customer  Sales Sales_Category
0     Asha  50000           High
1     Bala  30000         Medium
2   Chitra  15000            Low

In [13]:
#create a column called double_sales using lambda with apply function

df["Double_sales"]=df["Sales"].apply(lambda x:x*2)
df

  Customer  Sales Sales_Category  Double_sales
0     Asha  50000           High        100000
1     Bala  30000         Medium         60000
2   Chitra  15000            Low         30000

In [ ]:
#apply on entire dataframe
df.apply(lambda x:x*2)

       Customer   Sales Sales_Category  Double_sales
0      AshaAsha  100000       HighHigh        200000
1      BalaBala   60000   MediumMedium        120000
2  ChitraChitra   30000         LowLow         60000

In [ ]:
#apply with axis

#axis=0   operate on columns
#axis=1   operate on rows

df.apply(np.sum,axis=0)
# calculates sum column-wise

Customer    AshaBalaChitra
Sales                95000
dtype: object

In [8]:
data={
    "A":[10,20,30,40],
    "B":[1,2,3,4]
}

df=pd.DataFrame(data)
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4

In [ ]:
df.apply(lambda row:row["A"]+row["B"],axis=1)

#row wise operation

0    11
1    22
2    33
3    44
dtype: int64

In [18]:
data={"Revenue":[50000,30000],
       "Cost":[20000,15000]
       }
df=pd.DataFrame(data)
df

   Revenue   Cost
0    50000  20000
1    30000  15000

In [ ]:
df["Profit"]=df.apply(lambda row:row["Revenue"]-row["Cost"],axis=1)
df

   Revenue   Cost  Profit
0    50000  20000   30000
1    30000  15000   15000

In [28]:
import pandas as pd
import numpy as np

data={"Customer":["Asha","Bala","Chitra"],
      "Sales":["50000","30000","15000"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [29]:
#astype - type conversion
#example-sometimes numbers might be stored as strings

df["Sales"]=df["Sales"].astype(int) 
df.info()
#converting sales values datatype to numeric

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [30]:
data={"Customer":["Asha","Bala","Chitra"],
      "Sales":["50000","30000","missing"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [31]:
pd.to_numeric(df["Sales"],errors="coerce")

0    50000.0
1    30000.0
2        NaN
Name: Sales, dtype: float64

.apply is a last option or last resort because .apply runs python loops internally

This is not useful when there are millions of rows
In this case we would prefer vectorization(numpy vectorization)

numpy vectorization is faster